import {
  Package,
  Lock,
  CreditCard,
  Database,
  LayoutTemplate,
  Activity,
  LifeBuoy,
} from "lucide-react";

export const MODULE_CONFIG = [
  {
    id: "project",
    title: "Project Settings",
    icon: Package,
    color: "text-blue-500",
    description: "Core settings for your application identity.",
    documentation: [{ label: "Overview", slug: "overview" }],
    fields: [
      { name: "NEXT_PUBLIC_THEME", description: "The primary color theme for your application." },
      { name: "NEXT_PUBLIC_THEME_TYPE", description: "The default theme mode (light, dark, or system)." },
      { name: "NEXT_PUBLIC_SAAS_NAME", description: "The name of your SaaS application." },
      { name: "NEXT_PUBLIC_COMPANY_NAME", description: "The name of your company." },
      { name: "NEXT_PUBLIC_URL", description: "The URL of your application." },
    ] as const,
  },
  {
    id: "landing",
    title: "Landing Module",
    icon: LayoutTemplate,
    color: "text-purple-500",
    description: "Notion-backed CMS content.",
    documentation: [{ label: "Notion Setup", slug: "notion-setup" }],
    fields: [
      { name: "LANDING_DATABASE_ID", description: "Notion database ID for landing page content." },
      { name: "HERO_DATABASE_ID", description: "Notion database ID for hero section content." },
      { name: "FEATURE_DATABASE_ID", description: "Notion database ID for features section content." },
      { name: "TESTIMONIAL_DATABASE_ID", description: "Notion database ID for testimonials content." },
      { name: "PRICING_DATABASE_ID", description: "Notion database ID for pricing section content." },
      { name: "FAQ_DATABASE_ID", description: "Notion database ID for FAQ section content." },
      { name: "FOOTER_DATABASE_ID", description: "Notion database ID for footer content." },
      { name: "DOCUMENTATION_DATABASE_ID", description: "Notion database ID for documentation content." },
      { name: "NOTION_API_TOKEN", description: "Your Notion integration token." },
    ] as const,
  },
  {
    id: "auth",
    title: "Authentication Module",
    icon: Lock,
    color: "text-amber-500",
    description: "BetterAuth & OAuth providers.",
    documentation: [{ label: "Authentication Setup", slug: "authentication-overview" }],
    fields: [
      { name: "BETTER_AUTH_SECRET", description: "Secret key for BetterAuth." },
      { name: "AUTH_LINKEDIN_CLIENT_ID", description: "LinkedIn OAuth Client ID." },
      { name: "AUTH_LINKEDIN_CLIENT_SECRET", description: "LinkedIn OAuth Client Secret." },
      { name: "AUTH_GITHUB_CLIENT_ID", description: "GitHub OAuth Client ID." },
      { name: "AUTH_GITHUB_CLIENT_SECRET", description: "GitHub OAuth Client Secret." },
      { name: "AUTH_GOOGLE_CLIENT_ID", description: "Google OAuth Client ID." },
      { name: "AUTH_GOOGLE_CLIENT_SECRET", description: "Google OAuth Client Secret." },
      { name: "RESEND_API_KEY", description: "API Key for Resend email service." },
    ] as const,
  },
  {
    id: "support",
    title: "Support Module",
    icon: LifeBuoy,
    color: "text-rose-500",
    description: "Support email and booking.",
    documentation: [{ label: "Support", slug: "support" }],
    fields: [
      { name: "NEXT_PUBLIC_SUPPORT_MAIL", description: "Email address for support inquiries." },
      { name: "NEXT_PUBLIC_CALENDLY_BOOKING_URL", description: "URL for your Calendly booking page." },
    ] as const,
  },
  {
    id: "storage",
    title: "Storage Module",
    icon: Database,
    color: "text-cyan-500",
    description: "Postgres, Redis, and Blob storage.",
    documentation: [{ label: "Postgres", slug: "postgres" },
        { label: "Storage", slug: "storage" }, 
    ],
    fields: [
      { name: "BLOB_READ_WRITE_TOKEN", description: "Token for Vercel Blob storage." },
      { name: "DATABASE_URL", description: "Connection string for your PostgreSQL database." },
      { name: "UPSTASH_REDIS_REST_URL", description: "REST URL for Upstash Redis." },
      { name: "UPSTASH_REDIS_REST_TOKEN", description: "REST Token for Upstash Redis." },
    ] as const,
  },
  {
    id: "observability",
    title: "Observability Module",
    icon: Activity,
    color: "text-orange-500",
    description: "Telemetry and analytics.",
    documentation: [{ label: "Observability", slug: "observability" }],
    fields: [
      { name: "BETTERSTACK_TELEMETRY_SOURCE_TOKEN", description: "Source token for BetterStack telemetry." },
      { name: "BETTERSTACK_TELEMETRY_INGESTING_HOST", description: "Ingesting host for BetterStack telemetry." },
      { name: "NEXT_PUBLIC_GOOGLE_ANALYTICS_MEASUREMENT_ID", description: "Measurement ID for Google Analytics." },
    ] as const,
  },
  {
    id: "payment",
    title: "Payment Module",
    icon: CreditCard,
    color: "text-green-500",
    description: "Dodo Payments configuration.",
    documentation: [{ label: "Payments", slug: "payments" },
        { label: "Billing", slug: "billing" },
    ],
    fields: [
      { name: "DODO_PAYMENTS_API_KEY", description: "API Key for Dodo Payments." },
      { name: "DODO_PAYMENTS_WEBHOOK_KEY", description: "Webhook Key for Dodo Payments." },
      { name: "DODO_PAYMENTS_RETURN_URL", description: "Return URL after payment completion." },
      { name: "DODO_PAYMENTS_ENVIRONMENT", description: "Environment for Dodo Payments (test/live)." },
      { name: "DODO_CREDITS_PRODUCT_ID", description: "Product ID for credits in Dodo Payments." },
      { name: "NEXT_PUBLIC_DODO_PAYMENTS_URL", description: "Public URL for Dodo Payments." },
    ] as const,
  },
];